name:                snakell-game
version:             1.0.0.0
github:              "ufabc-bcc/23-q2-paradigmas-projetos-snakell"
license:             BSD3
author:              "David & Vittoria"
maintainer:          "david.pianura@aluno.ufabc.edu.br & vittoria.borotto@aluno.ufabc.edu.br"
copyright:           "2023 David & Vittoria"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ufabc-bcc/23-q2-paradigmas-projetos-snakell#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2.1
- gloss
- containers
- transformers
- mtl
- call == 0.1.4.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  snakell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snakell-game

tests:
  snakell-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snakell-game
